### ISSUE TITLE
User can search products to buy (ctrl/route)

### ISSUE THREAD

**Issue by Rian501** [chicken-sloths/bangazon-site-sprint3#18]
**Given** ~the user is authenticated~
**When** the user clicks on the search input field in the navigation bar
**And** the user types the name of a product
**When** pressed the enter key
**Then** products matching the keyword show in the page

- [ ] set up route if necessary
- [ ] set up ctrl to GET product with the name entered by the user

**Comment by DavidLarsKetch** [comment]
**Question**: Why does the user need to be authenticated?
