### ISSUE TITLE
User can view all product types(controller/route)

### ISSUE THREAD

**Issue by dhazlettjr** [chicken-sloths/bangazon-site-sprint3#31]
***Given*** a user is viewing any page on the Bangazon site
***When*** the user performs a gesture on the Product Types hyperlink
***Then*** the user will see a view containing a list of all product categories
***And*** next to the category name, the number of products in that category will be displayed
***And*** the first three products in the category will be displayed beneath each category, that are hyperlinks to the product detail

***Controllers***

The developer will implement a **GET** method in order to **get** all **product-types**.  The product-types will show the number of products next to the type, and the first ***3*** products in the list.

***Routes***

/product-types

- [ ] create necessary route
- [ ] build out ctrl to view all product types

**Comment by melissabell456** [comment]
duplicate
