### ISSUE TITLE
User can view all product types (view)

### ISSUE THREAD

**Issue by dhazlettjr** [chicken-sloths/bangazon-site-sprint3#35]
***Given*** a user is viewing any page on the Bangazon site
***When*** the user performs a gesture on the Product Types hyperlink
***Then*** the user will see a view containing a list of all product categories
***And*** next to the category name, the number of products in that category will be displayed
***And*** the first three products in the category will be displayed beneath each category, that are hyperlinks to the product detail

- [ ] set up pug view to display product types (product types should include the number of products of that type and a list of 3 products)

**Comment by jordan-castelloe** [comment]
accidental duplicate! Closing!

**Comment by jordan-castelloe** [comment]
dupes for real
