### ISSUE TITLE
User can view all products that are of a particular product type (ctrl/rt)

### ISSUE THREAD

**Issue by Rian501** [chicken-sloths/bangazon-site-sprint3#4]
**Given** the user is on any page of the Bangazon site
**When** the user performs a gesture on a product category name
**Then** a list of all products in that category will be displayed, with title, quantity, and price/unit

- [ ] ctrl should get products with the type selected from the drop down, a quantity > 0, and deleted as False

**Comment by DavidLarsKetch** [comment]
**Question**: do we want to display products that are sold out?
