### ISSUE TITLE
User can view product detail (rt/ctrl)

### ISSUE THREAD

**Issue by Rian501** [chicken-sloths/bangazon-site-sprint3#5]
**Given** user is viewing any page that contains a hyperlink for a product
**When** user performs a gesture on the product hyperlink
**Then** user will be shows the product detail page containing title, description, quantity available,  price/unit, and a button labeled *Add to Order*

**Given** 1+ users have purchased a product
**When** a user views the details
**Then** the quantity display should show how many are remaining, not how many were originally for sale

- [x] set up associated route (ie /product/:id})

- [x] set up ctrl to GET one product's detail (product detail should include remaining quantity of product)

- [x] set up ctrl to PUT new product on active product_order of current user

![image](https://user-images.githubusercontent.com/33636906/38998311-e7d60fb4-43b4-11e8-9386-48cb4e330477.png)

**Comment by DavidLarsKetch** [comment]
**MVP**: 
- Clicking 'Add to Order' adds 1 of that product
**Post-MVP**: 
- A 'quantity' input is provided to add more than one of a product
